language: python
sudo: false

# Currently (1/8/2019) python3.7 requires xenial
matrix:
  include:
    - python: 3.5
    - python: 3.6
    - python: 3.7
      dist: xenial

before_install:
  - uname -a

install:
  - pip install requests sphinx
  - pip install sphinxcontrib-programoutput sphinx_rtd_theme numpydoc

before_script:
  - python -V

script:
  - testing/run_scripts.sh
  - cd doc
  - make doctest
  - make html

notifications:
  email:
    on_success: change
    on_failure: always
